#pragma once
namespace System_Xml::System::Xml::Schema
{
	enum struct XsdBuilder_State : int32_t
	{
		Root = static_cast<int32_t>(0x0),
		Schema = static_cast<int32_t>(0x1),
		Annotation = static_cast<int32_t>(0x2),
		Include = static_cast<int32_t>(0x3),
		Import = static_cast<int32_t>(0x4),
		Element = static_cast<int32_t>(0x5),
		Attribute = static_cast<int32_t>(0x6),
		AttributeGroup = static_cast<int32_t>(0x7),
		AttributeGroupRef = static_cast<int32_t>(0x8),
		AnyAttribute = static_cast<int32_t>(0x9),
		Group = static_cast<int32_t>(0xA),
		GroupRef = static_cast<int32_t>(0xB),
		All = static_cast<int32_t>(0xC),
		Choice = static_cast<int32_t>(0xD),
		Sequence = static_cast<int32_t>(0xE),
		Any = static_cast<int32_t>(0xF),
		Notation = static_cast<int32_t>(0x10),
		SimpleType = static_cast<int32_t>(0x11),
		ComplexType = static_cast<int32_t>(0x12),
		ComplexContent = static_cast<int32_t>(0x13),
		ComplexContentRestriction = static_cast<int32_t>(0x14),
		ComplexContentExtension = static_cast<int32_t>(0x15),
		SimpleContent = static_cast<int32_t>(0x16),
		SimpleContentExtension = static_cast<int32_t>(0x17),
		SimpleContentRestriction = static_cast<int32_t>(0x18),
		SimpleTypeUnion = static_cast<int32_t>(0x19),
		SimpleTypeList = static_cast<int32_t>(0x1A),
		SimpleTypeRestriction = static_cast<int32_t>(0x1B),
		Unique = static_cast<int32_t>(0x1C),
		Key = static_cast<int32_t>(0x1D),
		KeyRef = static_cast<int32_t>(0x1E),
		Selector = static_cast<int32_t>(0x1F),
		Field = static_cast<int32_t>(0x20),
		MinExclusive = static_cast<int32_t>(0x21),
		MinInclusive = static_cast<int32_t>(0x22),
		MaxExclusive = static_cast<int32_t>(0x23),
		MaxInclusive = static_cast<int32_t>(0x24),
		TotalDigits = static_cast<int32_t>(0x25),
		FractionDigits = static_cast<int32_t>(0x26),
		Length = static_cast<int32_t>(0x27),
		MinLength = static_cast<int32_t>(0x28),
		MaxLength = static_cast<int32_t>(0x29),
		Enumeration = static_cast<int32_t>(0x2A),
		Pattern = static_cast<int32_t>(0x2B),
		WhiteSpace = static_cast<int32_t>(0x2C),
		AppInfo = static_cast<int32_t>(0x2D),
		Documentation = static_cast<int32_t>(0x2E),
		Redefine = static_cast<int32_t>(0x2F),
	};
}

