#pragma once
namespace System::System::Net
{
	enum struct HttpRequestHeader : int32_t
	{
		CacheControl = static_cast<int32_t>(0x0),
		Connection = static_cast<int32_t>(0x1),
		Date = static_cast<int32_t>(0x2),
		KeepAlive = static_cast<int32_t>(0x3),
		Pragma = static_cast<int32_t>(0x4),
		Trailer = static_cast<int32_t>(0x5),
		TransferEncoding = static_cast<int32_t>(0x6),
		Upgrade = static_cast<int32_t>(0x7),
		Via = static_cast<int32_t>(0x8),
		Warning = static_cast<int32_t>(0x9),
		Allow = static_cast<int32_t>(0xA),
		ContentLength = static_cast<int32_t>(0xB),
		ContentType = static_cast<int32_t>(0xC),
		ContentEncoding = static_cast<int32_t>(0xD),
		ContentLanguage = static_cast<int32_t>(0xE),
		ContentLocation = static_cast<int32_t>(0xF),
		ContentMd5 = static_cast<int32_t>(0x10),
		ContentRange = static_cast<int32_t>(0x11),
		Expires = static_cast<int32_t>(0x12),
		LastModified = static_cast<int32_t>(0x13),
		Accept = static_cast<int32_t>(0x14),
		AcceptCharset = static_cast<int32_t>(0x15),
		AcceptEncoding = static_cast<int32_t>(0x16),
		AcceptLanguage = static_cast<int32_t>(0x17),
		Authorization = static_cast<int32_t>(0x18),
		Cookie = static_cast<int32_t>(0x19),
		Expect = static_cast<int32_t>(0x1A),
		From = static_cast<int32_t>(0x1B),
		Host = static_cast<int32_t>(0x1C),
		IfMatch = static_cast<int32_t>(0x1D),
		IfModifiedSince = static_cast<int32_t>(0x1E),
		IfNoneMatch = static_cast<int32_t>(0x1F),
		IfRange = static_cast<int32_t>(0x20),
		IfUnmodifiedSince = static_cast<int32_t>(0x21),
		MaxForwards = static_cast<int32_t>(0x22),
		ProxyAuthorization = static_cast<int32_t>(0x23),
		Referer = static_cast<int32_t>(0x24),
		Range = static_cast<int32_t>(0x25),
		Te = static_cast<int32_t>(0x26),
		Translate = static_cast<int32_t>(0x27),
		UserAgent = static_cast<int32_t>(0x28),
	};
}

