#pragma once
namespace UnityEngine_IMGUIModule::UnityEngine
{
	enum struct TextEditor_TextEditOp : int32_t
	{
		MoveLeft = static_cast<int32_t>(0x0),
		MoveRight = static_cast<int32_t>(0x1),
		MoveUp = static_cast<int32_t>(0x2),
		MoveDown = static_cast<int32_t>(0x3),
		MoveLineStart = static_cast<int32_t>(0x4),
		MoveLineEnd = static_cast<int32_t>(0x5),
		MoveTextStart = static_cast<int32_t>(0x6),
		MoveTextEnd = static_cast<int32_t>(0x7),
		MovePageUp = static_cast<int32_t>(0x8),
		MovePageDown = static_cast<int32_t>(0x9),
		MoveGraphicalLineStart = static_cast<int32_t>(0xA),
		MoveGraphicalLineEnd = static_cast<int32_t>(0xB),
		MoveWordLeft = static_cast<int32_t>(0xC),
		MoveWordRight = static_cast<int32_t>(0xD),
		MoveParagraphForward = static_cast<int32_t>(0xE),
		MoveParagraphBackward = static_cast<int32_t>(0xF),
		MoveToStartOfNextWord = static_cast<int32_t>(0x10),
		MoveToEndOfPreviousWord = static_cast<int32_t>(0x11),
		SelectLeft = static_cast<int32_t>(0x12),
		SelectRight = static_cast<int32_t>(0x13),
		SelectUp = static_cast<int32_t>(0x14),
		SelectDown = static_cast<int32_t>(0x15),
		SelectTextStart = static_cast<int32_t>(0x16),
		SelectTextEnd = static_cast<int32_t>(0x17),
		SelectPageUp = static_cast<int32_t>(0x18),
		SelectPageDown = static_cast<int32_t>(0x19),
		ExpandSelectGraphicalLineStart = static_cast<int32_t>(0x1A),
		ExpandSelectGraphicalLineEnd = static_cast<int32_t>(0x1B),
		SelectGraphicalLineStart = static_cast<int32_t>(0x1C),
		SelectGraphicalLineEnd = static_cast<int32_t>(0x1D),
		SelectWordLeft = static_cast<int32_t>(0x1E),
		SelectWordRight = static_cast<int32_t>(0x1F),
		SelectToEndOfPreviousWord = static_cast<int32_t>(0x20),
		SelectToStartOfNextWord = static_cast<int32_t>(0x21),
		SelectParagraphBackward = static_cast<int32_t>(0x22),
		SelectParagraphForward = static_cast<int32_t>(0x23),
		Delete = static_cast<int32_t>(0x24),
		Backspace = static_cast<int32_t>(0x25),
		DeleteWordBack = static_cast<int32_t>(0x26),
		DeleteWordForward = static_cast<int32_t>(0x27),
		DeleteLineBack = static_cast<int32_t>(0x28),
		Cut = static_cast<int32_t>(0x29),
		Copy = static_cast<int32_t>(0x2A),
		Paste = static_cast<int32_t>(0x2B),
		SelectAll = static_cast<int32_t>(0x2C),
		SelectNone = static_cast<int32_t>(0x2D),
		ScrollStart = static_cast<int32_t>(0x2E),
		ScrollEnd = static_cast<int32_t>(0x2F),
		ScrollPageUp = static_cast<int32_t>(0x30),
		ScrollPageDown = static_cast<int32_t>(0x31),
	};
}

