#pragma once
namespace Assembly_CSharp
{
	enum struct GS : int32_t
	{
		STARTING = static_cast<int32_t>(0x0),
		GET_GAME_DATA = static_cast<int32_t>(0x1),
		WAITING_FOR_GAME_DATA = static_cast<int32_t>(0x2),
		GET_PLAYER_ID = static_cast<int32_t>(0x3),
		WAITING_FOR_AUTH_KEY = static_cast<int32_t>(0x4),
		WAITING_FOR_AUTH_TICKET = static_cast<int32_t>(0x5),
		WAITING_FOR_FB_TOKEN = static_cast<int32_t>(0x6),
		WAITING_FOR_NOVALINK_INIT = static_cast<int32_t>(0x7),
		CHECK_STEAM_TICKET = static_cast<int32_t>(0x8),
		RECV_SOCIAL_DATA = static_cast<int32_t>(0x9),
		LOADING_BUNDLES = static_cast<int32_t>(0xA),
		INIT = static_cast<int32_t>(0xB),
		AUTH = static_cast<int32_t>(0xC),
		WAITING_FOR_AUTH = static_cast<int32_t>(0xD),
		AUTH_ERROR = static_cast<int32_t>(0xE),
		LOADING = static_cast<int32_t>(0xF),
		MAINMENU = static_cast<int32_t>(0x10),
		CONNECTING = static_cast<int32_t>(0x11),
		GAME = static_cast<int32_t>(0x12),
		GAMEMENU = static_cast<int32_t>(0x13),
		BREAK = static_cast<int32_t>(0x14),
		STEAM_AUTH = static_cast<int32_t>(0x15),
		GET_PROFILE = static_cast<int32_t>(0x16),
		LOADING_PROFILE = static_cast<int32_t>(0x17),
		LOADING_BUNDLE = static_cast<int32_t>(0x18),
		GET_SESSION = static_cast<int32_t>(0x19),
		GET_FRIENDS_RATING = static_cast<int32_t>(0x1A),
		GET_FRIENDS_ONLINE = static_cast<int32_t>(0x1B),
		GAME_AUTH = static_cast<int32_t>(0x1C),
		GAME_LOADING_MAP = static_cast<int32_t>(0x1D),
		GAME_LOADING_MAP_CHANGES = static_cast<int32_t>(0x1E),
		GAME_LOADING_MY_PROFILE = static_cast<int32_t>(0x1F),
		GAME_VISUALIZING_MAP = static_cast<int32_t>(0x20),
		LOAD_PROFILE_COMLITE = static_cast<int32_t>(0x21),
		LOAD_BUNDLES_COMLITE = static_cast<int32_t>(0x22),
		GET_SESSION_COMLITE = static_cast<int32_t>(0x23),
		GET_FRIENDS_RATING_COMLITE = static_cast<int32_t>(0x24),
		GET_FRIENDS_ONLINE_COMLITE = static_cast<int32_t>(0x25),
		GET_STEAM_TICKET_COMLITE = static_cast<int32_t>(0x26),
		GAME_AUTH_COMPLITE = static_cast<int32_t>(0x27),
		GAME_LOAD_MAP_COMPLITE = static_cast<int32_t>(0x28),
		GAME_LOAD_MAP_CHANGES_COMPLITE = static_cast<int32_t>(0x29),
		GAME_LOAD_MY_PROFILE_COMPLITE = static_cast<int32_t>(0x2A),
		GAME_VISUALIZING_MAP_COMPLITE = static_cast<int32_t>(0x2B),
		SERVERUPDATES = static_cast<int32_t>(0x2C),
		LOADINGPROFILEERROR = static_cast<int32_t>(0x2D),
		GETSESSIONERROR = static_cast<int32_t>(0x2E),
		LOADINGBUNDLEERROR = static_cast<int32_t>(0x2F),
		GETFRIENDSRATINGERROR = static_cast<int32_t>(0x30),
		GETFRIENDSONLINEERROR = static_cast<int32_t>(0x31),
		GETSTEAMTICKETERROR = static_cast<int32_t>(0x32),
		CLIENTINITERROR = static_cast<int32_t>(0x33),
		BANNED = static_cast<int32_t>(0x34),
		GET_ID_ERROR = static_cast<int32_t>(0x35),
		NULL_ = static_cast<int32_t>(0x36),
	};
}

