#pragma once
namespace mscorlib::System
{
	enum struct ExceptionResource : int32_t
	{
		Argument_ImplementIComparable = static_cast<int32_t>(0x0),
		Argument_InvalidType = static_cast<int32_t>(0x1),
		Argument_InvalidArgumentForComparison = static_cast<int32_t>(0x2),
		Argument_InvalidRegistryKeyPermissionCheck = static_cast<int32_t>(0x3),
		ArgumentOutOfRange_NeedNonNegNum = static_cast<int32_t>(0x4),
		Arg_ArrayPlusOffTooSmall = static_cast<int32_t>(0x5),
		Arg_NonZeroLowerBound = static_cast<int32_t>(0x6),
		Arg_RankMultiDimNotSupported = static_cast<int32_t>(0x7),
		Arg_RegKeyDelHive = static_cast<int32_t>(0x8),
		Arg_RegKeyStrLenBug = static_cast<int32_t>(0x9),
		Arg_RegSetStrArrNull = static_cast<int32_t>(0xA),
		Arg_RegSetMismatchedKind = static_cast<int32_t>(0xB),
		Arg_RegSubKeyAbsent = static_cast<int32_t>(0xC),
		Arg_RegSubKeyValueAbsent = static_cast<int32_t>(0xD),
		Argument_AddingDuplicate = static_cast<int32_t>(0xE),
		Serialization_InvalidOnDeser = static_cast<int32_t>(0xF),
		Serialization_MissingKeys = static_cast<int32_t>(0x10),
		Serialization_NullKey = static_cast<int32_t>(0x11),
		Argument_InvalidArrayType = static_cast<int32_t>(0x12),
		NotSupported_KeyCollectionSet = static_cast<int32_t>(0x13),
		NotSupported_ValueCollectionSet = static_cast<int32_t>(0x14),
		ArgumentOutOfRange_SmallCapacity = static_cast<int32_t>(0x15),
		ArgumentOutOfRange_Index = static_cast<int32_t>(0x16),
		Argument_InvalidOffLen = static_cast<int32_t>(0x17),
		Argument_ItemNotExist = static_cast<int32_t>(0x18),
		ArgumentOutOfRange_Count = static_cast<int32_t>(0x19),
		ArgumentOutOfRange_InvalidThreshold = static_cast<int32_t>(0x1A),
		ArgumentOutOfRange_ListInsert = static_cast<int32_t>(0x1B),
		NotSupported_ReadOnlyCollection = static_cast<int32_t>(0x1C),
		InvalidOperation_CannotRemoveFromStackOrQueue = static_cast<int32_t>(0x1D),
		InvalidOperation_EmptyQueue = static_cast<int32_t>(0x1E),
		InvalidOperation_EnumOpCantHappen = static_cast<int32_t>(0x1F),
		InvalidOperation_EnumFailedVersion = static_cast<int32_t>(0x20),
		InvalidOperation_EmptyStack = static_cast<int32_t>(0x21),
		ArgumentOutOfRange_BiggerThanCollection = static_cast<int32_t>(0x22),
		InvalidOperation_EnumNotStarted = static_cast<int32_t>(0x23),
		InvalidOperation_EnumEnded = static_cast<int32_t>(0x24),
		NotSupported_SortedListNestedWrite = static_cast<int32_t>(0x25),
		InvalidOperation_NoValue = static_cast<int32_t>(0x26),
		InvalidOperation_RegRemoveSubKey = static_cast<int32_t>(0x27),
		Security_RegistryPermission = static_cast<int32_t>(0x28),
		UnauthorizedAccess_RegistryNoWrite = static_cast<int32_t>(0x29),
		ObjectDisposed_RegKeyClosed = static_cast<int32_t>(0x2A),
		NotSupported_InComparableType = static_cast<int32_t>(0x2B),
		Argument_InvalidRegistryOptionsCheck = static_cast<int32_t>(0x2C),
		Argument_InvalidRegistryViewCheck = static_cast<int32_t>(0x2D),
	};
}

