#pragma once
namespace mscorlib::System
{
	enum struct Environment_SpecialFolder : int32_t
	{
		MyDocuments = static_cast<int32_t>(0x5),
		Desktop = static_cast<int32_t>(0x0),
		MyComputer = static_cast<int32_t>(0x11),
		Programs = static_cast<int32_t>(0x2),
		Personal = static_cast<int32_t>(0x5),
		Favorites = static_cast<int32_t>(0x6),
		Startup = static_cast<int32_t>(0x7),
		Recent = static_cast<int32_t>(0x8),
		SendTo = static_cast<int32_t>(0x9),
		StartMenu = static_cast<int32_t>(0xB),
		MyMusic = static_cast<int32_t>(0xD),
		DesktopDirectory = static_cast<int32_t>(0x10),
		Templates = static_cast<int32_t>(0x15),
		ApplicationData = static_cast<int32_t>(0x1A),
		LocalApplicationData = static_cast<int32_t>(0x1C),
		InternetCache = static_cast<int32_t>(0x20),
		Cookies = static_cast<int32_t>(0x21),
		History = static_cast<int32_t>(0x22),
		CommonApplicationData = static_cast<int32_t>(0x23),
		System = static_cast<int32_t>(0x25),
		ProgramFiles = static_cast<int32_t>(0x26),
		MyPictures = static_cast<int32_t>(0x27),
		CommonProgramFiles = static_cast<int32_t>(0x2B),
		MyVideos = static_cast<int32_t>(0xE),
		NetworkShortcuts = static_cast<int32_t>(0x13),
		Fonts = static_cast<int32_t>(0x14),
		CommonStartMenu = static_cast<int32_t>(0x16),
		CommonPrograms = static_cast<int32_t>(0x17),
		CommonStartup = static_cast<int32_t>(0x18),
		CommonDesktopDirectory = static_cast<int32_t>(0x19),
		PrinterShortcuts = static_cast<int32_t>(0x1B),
		Windows = static_cast<int32_t>(0x24),
		UserProfile = static_cast<int32_t>(0x28),
		SystemX86 = static_cast<int32_t>(0x29),
		ProgramFilesX86 = static_cast<int32_t>(0x2A),
		CommonProgramFilesX86 = static_cast<int32_t>(0x2C),
		CommonTemplates = static_cast<int32_t>(0x2D),
		CommonDocuments = static_cast<int32_t>(0x2E),
		CommonAdminTools = static_cast<int32_t>(0x2F),
		AdminTools = static_cast<int32_t>(0x30),
		CommonMusic = static_cast<int32_t>(0x35),
		CommonPictures = static_cast<int32_t>(0x36),
		CommonVideos = static_cast<int32_t>(0x37),
		Resources = static_cast<int32_t>(0x38),
		LocalizedResources = static_cast<int32_t>(0x39),
		CommonOemLinks = static_cast<int32_t>(0x3A),
		CDBurning = static_cast<int32_t>(0x3B),
	};
}

