#pragma once
namespace UnityEngine_AnimationModule::UnityEngine
{
	enum struct HumanBodyBones : int32_t
	{
		Hips = static_cast<int32_t>(0x0),
		LeftUpperLeg = static_cast<int32_t>(0x1),
		RightUpperLeg = static_cast<int32_t>(0x2),
		LeftLowerLeg = static_cast<int32_t>(0x3),
		RightLowerLeg = static_cast<int32_t>(0x4),
		LeftFoot = static_cast<int32_t>(0x5),
		RightFoot = static_cast<int32_t>(0x6),
		Spine = static_cast<int32_t>(0x7),
		Chest = static_cast<int32_t>(0x8),
		UpperChest = static_cast<int32_t>(0x36),
		Neck = static_cast<int32_t>(0x9),
		Head = static_cast<int32_t>(0xA),
		LeftShoulder = static_cast<int32_t>(0xB),
		RightShoulder = static_cast<int32_t>(0xC),
		LeftUpperArm = static_cast<int32_t>(0xD),
		RightUpperArm = static_cast<int32_t>(0xE),
		LeftLowerArm = static_cast<int32_t>(0xF),
		RightLowerArm = static_cast<int32_t>(0x10),
		LeftHand = static_cast<int32_t>(0x11),
		RightHand = static_cast<int32_t>(0x12),
		LeftToes = static_cast<int32_t>(0x13),
		RightToes = static_cast<int32_t>(0x14),
		LeftEye = static_cast<int32_t>(0x15),
		RightEye = static_cast<int32_t>(0x16),
		Jaw = static_cast<int32_t>(0x17),
		LeftThumbProximal = static_cast<int32_t>(0x18),
		LeftThumbIntermediate = static_cast<int32_t>(0x19),
		LeftThumbDistal = static_cast<int32_t>(0x1A),
		LeftIndexProximal = static_cast<int32_t>(0x1B),
		LeftIndexIntermediate = static_cast<int32_t>(0x1C),
		LeftIndexDistal = static_cast<int32_t>(0x1D),
		LeftMiddleProximal = static_cast<int32_t>(0x1E),
		LeftMiddleIntermediate = static_cast<int32_t>(0x1F),
		LeftMiddleDistal = static_cast<int32_t>(0x20),
		LeftRingProximal = static_cast<int32_t>(0x21),
		LeftRingIntermediate = static_cast<int32_t>(0x22),
		LeftRingDistal = static_cast<int32_t>(0x23),
		LeftLittleProximal = static_cast<int32_t>(0x24),
		LeftLittleIntermediate = static_cast<int32_t>(0x25),
		LeftLittleDistal = static_cast<int32_t>(0x26),
		RightThumbProximal = static_cast<int32_t>(0x27),
		RightThumbIntermediate = static_cast<int32_t>(0x28),
		RightThumbDistal = static_cast<int32_t>(0x29),
		RightIndexProximal = static_cast<int32_t>(0x2A),
		RightIndexIntermediate = static_cast<int32_t>(0x2B),
		RightIndexDistal = static_cast<int32_t>(0x2C),
		RightMiddleProximal = static_cast<int32_t>(0x2D),
		RightMiddleIntermediate = static_cast<int32_t>(0x2E),
		RightMiddleDistal = static_cast<int32_t>(0x2F),
		RightRingProximal = static_cast<int32_t>(0x30),
		RightRingIntermediate = static_cast<int32_t>(0x31),
		RightRingDistal = static_cast<int32_t>(0x32),
		RightLittleProximal = static_cast<int32_t>(0x33),
		RightLittleIntermediate = static_cast<int32_t>(0x34),
		RightLittleDistal = static_cast<int32_t>(0x35),
		LastBone = static_cast<int32_t>(0x37),
	};
}

