#pragma once
namespace Rewired_Core
{
	enum struct obyfbEVyyVcqOGAFVygdmbODjCD_VQETPQVuegnSuVSWyLMimklaZtz : uint32_t
	{
		UTbJJwFWqviHChgcSViYCoSAOQx = static_cast<uint32_t>(0x0),
		NmzkooUiuwCFgDCmBrdmTEotSaxp = static_cast<uint32_t>(0x100),
		sqQAZqkTonlFJlvIsstefGrYocW = static_cast<uint32_t>(0x101),
		VkTWrctwTSnQetMpYlBmRSEFJuB = static_cast<uint32_t>(0x102),
		dCGDsSckMQIcXEeqIuteqcWIJjEv = static_cast<uint32_t>(0x103),
		xIGGpxTCpheOcpmsvjGSrvmvsHG = static_cast<uint32_t>(0x104),
		bbHBNHDbyTVLJeSYoQWieSGpCPpR = static_cast<uint32_t>(0x105),
		qKBizMfEUYBqGyhuuFpoTniLSVZ = static_cast<uint32_t>(0x106),
		rpoUVRvaJtIpTbKbDcmGOXUdhGeb = static_cast<uint32_t>(0x200),
		PsSmVhBxhZRCmesWaQrOyhpTcTm = static_cast<uint32_t>(0x201),
		vPBVMkOTThPrMtatmKHkHKvBfBkA = static_cast<uint32_t>(0x300),
		nqdcNSOOlMVmVjnRgBmCSFRAfPEb = static_cast<uint32_t>(0x301),
		ogGVbpYqofUGtdXGyBHKdrcaEKx = static_cast<uint32_t>(0x302),
		ZnqakCZsExSqBNWfejTQfESqaGGg = static_cast<uint32_t>(0x303),
		IjHcUOoQIvBGJrAaeTArZmWHcLf = static_cast<uint32_t>(0x400),
		GDqbbFrefnhlUqfOXWarPSkQueU = static_cast<uint32_t>(0x401),
		vBMGOKAzQdXUoPhPpqQxCTWJahjo = static_cast<uint32_t>(0x402),
		DPJPqZyxSPRalGlcvwBDcbOQWED = static_cast<uint32_t>(0x403),
		hMqnTHDtbWssGKeNiPkkGNQEBRv = static_cast<uint32_t>(0x600),
		GHlzVPdAlqfyqyzepNblPGhfBFx = static_cast<uint32_t>(0x601),
		JvmsylZNzPcDQCJcgAIQIgAauOJq = static_cast<uint32_t>(0x602),
		mLuVjRknlJPVUlLFwpgHAuEswUD = static_cast<uint32_t>(0x603),
		HHycLcHuKJMmlvnHYoBXVXdHXsbu = static_cast<uint32_t>(0x604),
		oyOhXVUenoKtCJXdCbDbbLpAtjK = static_cast<uint32_t>(0x605),
		NbXVyvUrPkDTfRdclFKofIeZXVj = static_cast<uint32_t>(0x606),
		bvELGehoJzOFLvRnQtynAilmoDu = static_cast<uint32_t>(0x650),
		BaGDSISiWFzdjojbyqzzlhokmnu = static_cast<uint32_t>(0x651),
		njoAcnTqzCoLKMKvMfXaMzzLlGP = static_cast<uint32_t>(0x652),
		QwNGDAvzSFjpBGvrntcOhpAmMSh = static_cast<uint32_t>(0x653),
		pnvopXOgMCBxWKuaasZSguSJGwP = static_cast<uint32_t>(0x654),
		sXHetXgDjVIqYLGyqweFcoNjCooe = static_cast<uint32_t>(0x655),
		enWKNpOuGFwdcPzANKkvzNqgeNIh = static_cast<uint32_t>(0x700),
		jPmyyvSloVXihrBbWCGWjDKYFOFC = static_cast<uint32_t>(0x701),
		BqsHsLqUHkGRetErARYApKoKCNH = static_cast<uint32_t>(0x702),
		lSERlwiopZzqODNLedvIcrTiLCqG = static_cast<uint32_t>(0x800),
		QcVvfYsjzMyirNMUOHqwzbwcifJ = static_cast<uint32_t>(0x801),
		ekFCuITJhIBXxhPURzcISpualHuh = static_cast<uint32_t>(0x802),
		sGKSNJqGxWbSNZneBmGXERZeFSt = static_cast<uint32_t>(0x900),
		dcIJabpEjAeUnARvYNJdtUMdOsuO = static_cast<uint32_t>(0x1000),
		flCxGCZbwTcfeUalNJEKLHYNoKM = static_cast<uint32_t>(0x2000),
		fRgSzmkMtRlJBELpSIYMuWTkiNv = static_cast<uint32_t>(0x8000),
		eikbQDbYopycXffxkkKlWCqykMIB = static_cast<uint32_t>(0xFFFF),
	};
}

