#pragma once
namespace Rewired_Core::Rewired
{
	enum struct InputActionEventType : int32_t
	{
		Update = static_cast<int32_t>(0x0),
		ButtonPressed = static_cast<int32_t>(0x1),
		ButtonUnpressed = static_cast<int32_t>(0x2),
		ButtonJustPressed = static_cast<int32_t>(0x3),
		ButtonJustReleased = static_cast<int32_t>(0x4),
		ButtonDoublePressed = static_cast<int32_t>(0x5),
		ButtonJustDoublePressed = static_cast<int32_t>(0x6),
		ButtonPressedForTime = static_cast<int32_t>(0x7),
		ButtonJustPressedForTime = static_cast<int32_t>(0x8),
		ButtonPressedForTimeJustReleased = static_cast<int32_t>(0x9),
		ButtonShortPressed = static_cast<int32_t>(0xA),
		ButtonJustShortPressed = static_cast<int32_t>(0xB),
		ButtonShortPressJustReleased = static_cast<int32_t>(0xC),
		ButtonLongPressed = static_cast<int32_t>(0xD),
		ButtonJustLongPressed = static_cast<int32_t>(0xE),
		ButtonLongPressJustReleased = static_cast<int32_t>(0xF),
		ButtonRepeating = static_cast<int32_t>(0x10),
		NegativeButtonPressed = static_cast<int32_t>(0x11),
		NegativeButtonUnpressed = static_cast<int32_t>(0x12),
		NegativeButtonJustPressed = static_cast<int32_t>(0x13),
		NegativeButtonJustReleased = static_cast<int32_t>(0x14),
		NegativeButtonDoublePressed = static_cast<int32_t>(0x15),
		NegativeButtonJustDoublePressed = static_cast<int32_t>(0x16),
		NegativeButtonPressedForTime = static_cast<int32_t>(0x17),
		NegativeButtonJustPressedForTime = static_cast<int32_t>(0x18),
		NegativeButtonPressedForTimeJustReleased = static_cast<int32_t>(0x19),
		NegativeButtonShortPressed = static_cast<int32_t>(0x1A),
		NegativeButtonJustShortPressed = static_cast<int32_t>(0x1B),
		NegativeButtonShortPressJustReleased = static_cast<int32_t>(0x1C),
		NegativeButtonLongPressed = static_cast<int32_t>(0x1D),
		NegativeButtonJustLongPressed = static_cast<int32_t>(0x1E),
		NegativeButtonLongPressJustReleased = static_cast<int32_t>(0x1F),
		NegativeButtonRepeating = static_cast<int32_t>(0x20),
		AxisActive = static_cast<int32_t>(0x21),
		AxisInactive = static_cast<int32_t>(0x22),
		AxisRawActive = static_cast<int32_t>(0x23),
		AxisRawInactive = static_cast<int32_t>(0x24),
		AxisActiveOrJustInactive = static_cast<int32_t>(0x25),
		AxisRawActiveOrJustInactive = static_cast<int32_t>(0x26),
		ButtonDoublePressJustReleased = static_cast<int32_t>(0x64),
		ButtonSinglePressed = static_cast<int32_t>(0x65),
		ButtonJustSinglePressed = static_cast<int32_t>(0x66),
		ButtonSinglePressJustReleased = static_cast<int32_t>(0x67),
		NegativeButtonDoublePressJustReleased = static_cast<int32_t>(0x96),
		NegativeButtonSinglePressed = static_cast<int32_t>(0x97),
		NegativeButtonJustSinglePressed = static_cast<int32_t>(0x98),
		NegativeButtonSinglePressJustReleased = static_cast<int32_t>(0x99),
	};
}

