#pragma once
namespace Rewired_Core::Rewired
{
	enum struct InputPlatform : int32_t
	{
		JeCsuDmzHypNAKQRUrkSJqoqgFu = static_cast<int32_t>(0x0),
		ChYKTANuNWZkOOjlIuhyYRzmDZN = static_cast<int32_t>(0x1),
		cPSGiHiPGLsOJNyOnayEqbAGEnXh = static_cast<int32_t>(0x2),
		ohdYsUNNwwXndeXjpFMuEYkaRwh = static_cast<int32_t>(0x3),
		toggRwcKqoXrrUsFtPkNnklDoaWB = static_cast<int32_t>(0x4),
		hGLTueioCLyNIstdbaKghIgjarLi = static_cast<int32_t>(0x5),
		TwYaBKBHiSXlcqwcBkRHaDKIPJa = static_cast<int32_t>(0x6),
		irqpGDqCUWVPqRAKEqMiInxcZjv = static_cast<int32_t>(0x7),
		tFhuNEugppZwGIPuMxoAUMvcaty = static_cast<int32_t>(0x8),
		mvgjGdBuIkIXJvZRKOybffvmjVw = static_cast<int32_t>(0x9),
		shLFEqKhmQFerCiMdyOEPNXJANYG = static_cast<int32_t>(0xA),
		PdsUxYJpuijIecYPucKpQzPLtho = static_cast<int32_t>(0xB),
		phOaltEZsLreWVokZKaEojrcxnLS = static_cast<int32_t>(0xC),
		JiBWvXHEFycTMPraKwYwNkzpLzG = static_cast<int32_t>(0xD),
		wfnehutVmgoioZWVAEQdTZZopnL = static_cast<int32_t>(0xE),
		ZmQQCiqUOXjPTRPyHsjaLCGwOAd = static_cast<int32_t>(0xF),
		WoGZukjlGtYWrPLBTgIAeYYFsJb = static_cast<int32_t>(0x10),
		RzvnajFsJESWgdamBpIiFvbFRRi = static_cast<int32_t>(0x11),
		nBHigqdMVCtmUnBDDfsyCdBhbDE = static_cast<int32_t>(0x12),
		mihTGoXiAQAhgaBaepQxnttyXvTO = static_cast<int32_t>(0x13),
		XCOeMflVIdwQzCmiyLwVqObqTqj = static_cast<int32_t>(0x14),
		lbImZldjgEBupobEYfhTehyglkS = static_cast<int32_t>(0x15),
		HNhdNLZVHldHFRrXNCGXLGKvlH = static_cast<int32_t>(0x16),
		ovdoPhMSDosPshnIlZwEUBSbcbfJ = static_cast<int32_t>(0x17),
		nqwmxnSkgTMAsznNSqMRaIJWvgz = static_cast<int32_t>(0x18),
		vuGWJKwUhcfMNEmGqcWvgXPPSCb = static_cast<int32_t>(0x19),
		lYossmYriuTTCrPkhSeUJkoBiWo = static_cast<int32_t>(0x1A),
		sVbhJoWkFpkPgxppAiuKLQfahgI = static_cast<int32_t>(0x1B),
		hPQYYdNYSALzTUcgLlBvQkdsUxo = static_cast<int32_t>(0x1C),
		rTetWYaFgMGNngViXGNAvDTuzyh = static_cast<int32_t>(0x1D),
		gOUqQFxhvmgQVJMmnLjTmjKsaCE = static_cast<int32_t>(0x1E),
		NfHrUbkcfdEgiKOMxkIuiMtTfWOs = static_cast<int32_t>(0x1F),
		bojJfQrQcFoQUiAkjerIdQMiriXo = static_cast<int32_t>(0x20),
		zYErUZLyOXONCYJXwIqHFNWXqLr = static_cast<int32_t>(0x21),
		YJfgJlVJsFcyDKXBkNToAHRvKpG = static_cast<int32_t>(0x22),
		OFrKwFgroUVWNAMIKymWNbRMlK = static_cast<int32_t>(0x23),
		qKEfPfboVuWQzbDNlLMipgKXIbxQ = static_cast<int32_t>(0x24),
		QlYhopRsDmNdEoftVDjkDDFWMdT = static_cast<int32_t>(0x25),
		NJNHXULHMDjDchbBBDlVEiyjDwsj = static_cast<int32_t>(0x26),
		uCcynDlnwzzicNdlNLUSieJDSJM = static_cast<int32_t>(0x27),
		wfaaNYgLHdeAPdKpsnfVLLWOOeIr = static_cast<int32_t>(0x28),
		DuyHevunExYCBHbQiFsjYFeFEGBA = static_cast<int32_t>(0x29),
		TfUQOVXOLIjnqcfnGmAJRuOARMc = static_cast<int32_t>(0x2A),
	};
}

